apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-service 
  # nama-service
  name: order-service
spec:
  ports:
    - name: order-service-svc 
      port: 3000
      targetPort: 3000
      nodePort: 30300
  selector:
    app: order-service 
  type: NodePort