version: '3.8'

services:
  item-app:
    # image: docker.pkg.github.com/kecoax-code/a433-microservices/item-app:v1
    image: ghcr.io/kecoax-code/a433-microservices/item-app:v1
    ports:
      - 80:8080
    depends_on:
      - item-db
    restart: always
    networks:
      - item-network

  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db
    restart: always
    networks:
      - item-network

networks:
  item-network:
    driver: bridge

volumes:
  app-db:
