version: 2.1
jobs:
  lint-dockerfile:
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - run:
          name: Install hadolint
          command: |
            curl -sL -o hadolint "https://github.com/hadolint/hadolint/releases/latest/download/hadolint-$(uname -s)-$(uname -m)"
            chmod +x hadolint
            sudo mv hadolint /usr/local/bin/
      - run:
          name: Lint Dockerfile
          command: |
            hadolint Dockerfile

  build-app-karsajobs-ui:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - run:
          name: Build and push image
          command: |
            docker login ghcr.io -u $GITHUB_USER -p $GITHUB_TOKEN
            docker build -t ghcr.io/kecoax-code/a433-microservices/karsajobs-ui:latest .
            docker push ghcr.io/kecoax-code/a433-microservices/karsajobs-ui:latest

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile
