apiVersion: v1 
kind: Service
metadata:
  labels:
    app: shipping-service
  # nama-service
  name: shipping-service
spec:
  ports:
    - name: shipping-service-svc
      port: 3001
      targetPort: 3001 
      nodePort: 30301 
  selector:
    app: shipping-service
  type: NodePort