apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui
spec:
  type: NodePort
  selector:
    app: karsajobs-ui
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30081
