apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  serviceName: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq 
    spec:
      containers:
        - name: rabbitmq
          # image-repo
          image: rabbitmq:3.11-management
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq 
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data 
      spec:
        accessModes:
          - "ReadWriteOnce" 
        resources:
          requests:
            storage: 1Gi 